version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    routes:
      - 'notify.irc-channel.#demo-ci.on-any',
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
          - push
          - release 
    payload:
      maxRunTime: 3600
      image: python 
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          pip install 'taskcluster>=4,<5' &&
          git clone {{event.head.repo.url}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.head.sha}} && python /repo/tools/demo.py &&  /repo/tools/demo.sh 
    metadata:
      name: 'demo-taskcluster'
      description: ''
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators
