version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    routes:
      - 'notify.irc-channel.#demo-ci.on-any'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
          - push
          - release 
    payload:
      maxRunTime: 3600
      image: python 
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.head.sha}} &&  /repo/tools/demo.sh 
    metadata:
      name: 'demo-taskcluster'
      description: ''
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
    scopes:
    - "queue:route:notify.irc-channel.#demo-ci.on-any",
    - "queue:route:statuses",
allowPullRequests: collaborators
