version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
    payload:
      maxRunTime: 3600
      image: node
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo 
          && git config advice.detachedHead false
          && git checkout ${event.pull_request.head.sha}
          && tools/demo.sh
    metadata:
      name: demo-tc
      description: ''
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators

